Channel
SOF3/await-generator pull request #114
Opened 2022-03-05 16:38 UTC by SOF3

2022-03-15 00:18 UTC, Endermanbugzjfc commented
Do I just need review to review the API.

2022-03-15 12:03 UTC, SOF3 commented
> Do I just need review to review the API?

Yeah, I think the implementation is correct, but it'd be great if you can have a look too.

2022-03-17 00:28 UTC, Endermanbugzjfc requested changes

2022-03-17 00:28 UTC, Endermanbugzjfc commented on await-generator/src/SOFe/AwaitGenerator/Channel.php
> +	 * Send a value to the channnel
```suggestion
	 * Send a value to the channel
```

2022-03-17 01:06 UTC, Endermanbugzjfc approved these changes

2022-03-18 01:15 UTC, merged