Allows promise resolver to have no arguments
SOF3/await-generator pull request #152
Opened 2022-06-09 16:58 UTC by keopiwauyu

await generator mkae phpstan confuse i not know good fix way so i do this
https://github.com/SOF3/Capital/runs/6087223450?check_suite_focus=true#step:4:248

https://github.com/SOF3/await-generator/blob/master/await-generator/virion.yml VERSION 3.4.2

2022-06-09 16:59 UTC, keopiwauyu commented
@SOF3 i edit virion.yml but you no approve& merge pr pls edit yoursel

2022-06-09 17:12 UTC, keopiwauyu commented
why php unit and phpstan run so long very long

2022-06-10 01:41 UTC, SOF3 requested changes

2022-06-10 01:41 UTC, SOF3 commented on await-generator/src/SOFe/AwaitGenerator/Await.php
> +	 * @param Closure(Closure(T): void|Closure(): void, Closure(Throwable): void): void $closure
```suggestion
	 * @param Closure(Closure(T=): void, Closure(Throwable): void): void $closure
```

2022-06-10 06:13 UTC, SOF3 approved these changes

2022-06-10 06:13 UTC, merged

2022-06-10 06:14 UTC, SOF3 commented
> why php unit and phpstan run so long very long

because it requires approval.

2022-06-10 06:24 UTC, keopiwauyu commented
> I intend to deprecate the current confusing parameter format and have something simpler like `Generator<Await, Await, Await, R>` at the phpstan level.

What ?

2022-06-10 09:49 UTC, SOF3 commented
> > I intend to deprecate the current confusing parameter format and have something simpler like `Generator<Await, Await, Await, R>` at the phpstan level.
> 
> What ?

the current API requires users to pass a recursive type into Await::all() etc. This doesn't work correctly with phpstan and users have to manually suppress the error.

2022-06-10 13:49 UTC, keopiwauyu commented
> > > I intend to deprecate the current confusing parameter format and have something simpler like `Generator<Await, Await, Await, R>` at the phpstan level.
> > 
> > 
> > What ?
> 
> the current API requires users to pass a recursive type into Await::all() etc. This doesn't work correctly with phpstan and users have to manually suppress the error.

PHPSTAN VRRY BAD

2022-06-10 13:50 UTC, keopiwauyu commented
@SOF3 pls pls make releaee tag i use in capital to fix phpstan err