Chinese README
SOF3/await-generator pull request #164
Opened 2022-08-08 18:11 UTC by Endermanbugzjfc

2022-08-09 01:33 UTC, SOF3 commented
why did you replace the original content instead of creating a new file?

2022-08-09 06:28 UTC, SOF3 commented on README.md
> +Eng | [繁](README.zho.md) | [簡](README.chs.md)
simplified doesn't exist yet right?

2022-08-10 01:39 UTC, SOF3 commented on README.md
> +Eng | [繁](README.zho.md) | [簡](README.chs.md)
that'd mean one of the two has to become a source of truth. Does that sound like a good idea?

2022-08-10 03:32 UTC, SOF3 commented on README.md
> +Eng | [繁](README.zho.md) | [簡](README.chs.md)
@Endermanbugzjfc it just feels too complex to setup a workflow just for translating the document.

2022-08-10 04:52 UTC, SOF3 requested changes

2022-08-10 04:52 UTC, SOF3 commented on zho/README.md
> +await-generator 會在 `Await::f2c` method 開始進行異步代碼流控制，它接受一般的回調語法，這樣就無需再 <!-- TODO: help wanted-->
`Await::f2c` doesn't accept callback syntax. I am just saying that you can use this wrapper to create callback style API.

2022-08-10 04:52 UTC, SOF3 commented on zho/README.md
> +await-generator 也有很多經常的坑人的地方：
```suggestion
await-generator 也有很多經常坑人的地方：
```

2022-08-10 04:52 UTC, SOF3 commented on zho/README.md
> +- 忘了 `yield from Generator<void>` 的結果是代碼會毫無作用；
```suggestion
- 忘了 `yield from` 的代碼會毫無作用；
```

2022-08-10 04:52 UTC, SOF3 commented on zho/README.md
> +  (e.g. `Await::promise(fn($resolve) => null)`)；
delete these two lines?

2022-08-10 04:52 UTC, SOF3 commented on zho/README.md
> +儘管地方會導致一些問題， await-generator 的設計模式依然比「回調地獄」更難出 bug 。
```suggestion
儘管一些地方會導致問題， await-generator 的設計模式出 bug的機會依然比「回調地獄」少 。
```

2022-08-10 20:05 UTC, Endermanbugzjfc commented
Btw line breaks will cause space in the middle of sentences. Shall we make the sentence format uniform? Maybe one space after each full stop?

2022-08-11 05:30 UTC, SOF3 requested changes

2022-08-11 05:30 UTC, SOF3 commented on zho/README.md
> +### 連貫的狀態
```suggestion
### 並發狀態
```

2022-08-11 05:30 UTC, SOF3 commented on zho/README.md
> +的確，這樣在呼叫它時給予了其他執行者呼叫任何可修改你狀態的函數。
```suggestion
調用函數時固然給予了實現者調用可修改狀態的函數的可能性，
```

2022-08-11 05:30 UTC, SOF3 commented on zho/README.md
> +但是一個正常的、合理的構造，例如 HTTP 請求所呼叫的函數不應會修改你程式庫的私有狀態。
```suggestion
但是一個正常的、合理的實現，例如 HTTP 請求所調用的函數不應修改你程式庫的私有狀態。
```

2022-08-11 05:30 UTC, SOF3 commented on zho/README.md
> +因為當一個光纖被暫停後，剩下的仍然可以修改內部狀態。
```suggestion
因為當一個纖程被暫停後，其他纖程仍然可以修改你的內部狀態。
```

2022-08-11 05:30 UTC, SOF3 commented on zho/README.md
> +但是這個假設對於 fibers 來說並不成立
```suggestion
但是這個假設對於 fibers 來說並不成立，
```

2022-08-11 05:30 UTC, SOF3 commented on zho/README.md
> +每次你呼叫任何*可能*會被暫停的函數時，你都必須檢查內部屬性的可能變化。
```suggestion
每次你調用任何*可能*會被暫停的函數時，你都必須檢查內部狀態的可能變化。
```

2022-08-11 05:38 UTC, SOF3 commented
Please standardize a few terms

Fibers => 纖程 (not optical fibers!!! -.-)
implementation => 實現
function call => 函數調用

2022-08-11 10:23 UTC, Endermanbugzjfc commented on zho/README.md
> +的確，這樣在呼叫它時給予了其他執行者呼叫任何可修改你狀態的函數。
> Suggested change
> 的確，這樣在呼叫它時給予了其他執行者呼叫任何可修改你狀態的函數。
> 調用函數時固然給予了實現者調用可修改狀態的函數的可能性，

```diff
- 狀態的函數的可能性
+ 狀態函數的可能性
```
Two `的`s.

2022-08-11 10:25 UTC, Endermanbugzjfc commented on zho/README.md
> +但是一個正常的、合理的構造，例如 HTTP 請求所呼叫的函數不應會修改你程式庫的私有狀態。
Oh I forgot to change 私有狀態 to 內部狀態.

2022-08-11 15:26 UTC, Endermanbugzjfc commented on zho/README.md
> +的確，這樣在呼叫它時給予了其他執行者呼叫任何可修改你狀態的函數。
```suggestion
調用函數時固然給予了實現者調用可修改狀態函數的可能性，
```

2022-08-11 15:27 UTC, Endermanbugzjfc commented on zho/README.md
> +但是一個正常的、合理的構造，例如 HTTP 請求所呼叫的函數不應會修改你程式庫的私有狀態。
```suggestion
但是一個正常的、合理的實現，例如 HTTP 請求所調用的函數不應修改你程式庫的內部狀態。
```

2022-08-11 15:30 UTC, Endermanbugzjfc commented on zho/README.md
> +### 連貫的狀態
Why was this suggestion block not showing up in the Files tab? And 並發狀態 sounds so abstract...

2022-08-11 15:30 UTC, Endermanbugzjfc commented
> Fibers => 纖程 (not optical fibers!!! -.-)
Blame DeepL heh.

2022-08-21 14:24 UTC, Endermanbugzjfc commented
How to mute this bot?

2022-09-11 15:05 UTC, Endermanbugzjfc commented
@SOF3 I think a `book-translation` branch should be created. Translations live in that branch while the English version will still be kept on master.

2022-09-11 15:05 UTC, Endermanbugzjfc commented
I will create another PR for the book translations.

2022-09-11 15:37 UTC, BluSimmon approved these changes

2022-09-11 15:41 UTC, BluSimmon approved these changes

2022-09-11 22:17 UTC, Endermanbugzjfc commented
I will not translate the code in README.md nor to add explaination comments until someone complains about this.

2022-09-12 03:32 UTC, SOF3 requested changes
Please also update the corresponding changes for chs

2022-09-12 03:32 UTC, SOF3 commented on zho/README.md
> +## 使用後的代碼可以維持「backward compatibility 回溯相容性」嗎？
```suggestion
## 使用後的代碼可以維持回溯相容性嗎？
```

no need to keep the english term

2022-09-12 03:32 UTC, SOF3 commented on zho/README.md
> +是的， await-generator 不會對已有的程式接口（API）造成任何限制。
```suggestion
是的， await-generator 不會對已有的接口造成任何限制。
```

2022-09-12 03:32 UTC, SOF3 commented on zho/README.md
> +await-generator 會在 `Await::f2c` method 開始進行異步代碼流控制，你可以將它視為「等待式」至「回調式」的轉接頭。
```suggestion
await-generator 會在 `Await::f2c` 開始進行異步代碼流控制，你可以將它視為「等待式」至「回調式」的轉接頭。
```

2022-09-12 03:32 UTC, SOF3 commented on zho/README.md
> +> 因為有人為了實現一個界面而調用 Fiber::suspend() 。
```suggestion
> 因為有人實現一個界面時調用了 `Fiber::suspend() ` 。
```

2022-09-12 03:32 UTC, SOF3 commented on zho/README.md
> +> 那個框架肯定還沒把它給清除。
```suggestion
> 框架肯定還沒把它給超時清除。
```

2022-09-12 04:09 UTC, Endermanbugzjfc commented
Sorry, I have not yet figure out how to batch suggestions on mobile app...

2022-09-12 04:22 UTC, Endermanbugzjfc commented
1 sec,

2022-09-14 14:46 UTC, Endermanbugzjfc commented
> Changes requested
What changes? I committed all.

2022-09-14 15:26 UTC, SOF3 approved these changes

2022-09-14 15:26 UTC, merged